console.log("\n\n <<<<<< App.js >>>>>> \n\n")
const {add} = require("./add")
console.log("\n")
const {sub} = require("./subtract")
console.log("\n")
const {multiply} = require("./multiply")
console.log("\n")
const {division} = require("./division")
console.log("\n")


add(10,20)
console.log("========================= \n")
sub(20,4)
console.log("========================= \n")
multiply(4,8)
console.log("========================= \n")
division(4,45)
console.log("========================= \n")